Route133_MapScripts:: @ 81F75A2
	.byte 0

Route133_EventScript_Franklin:: @ 81F75A3
	trainerbattle_double TRAINER_FRANKLIN, Route133_Text_FranklinIntro, Route133_Text_FranklinDefeat, Doubles_Text_NotEnoughMons
	msgbox Route133_Text_FranklinPostBattle, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_Debra:: @ 81F75BA
	trainerbattle_double TRAINER_DEBRA, Route133_Text_DebraIntro, Route133_Text_DebraDefeat, Doubles_Text_NotEnoughMons
	msgbox Route133_Text_DebraPostBattle, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_Linda:: @ 81F75D1
	trainerbattle_double TRAINER_LINDA, Route133_Text_LindaIntro, Route133_Text_LindaDefeat, Doubles_Text_NotEnoughMons
	msgbox Route133_Text_LindaPostBattle, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_Warren:: @ 81F75E8
	trainerbattle_double TRAINER_WARREN, Route133_Text_WarrenIntro, Route133_Text_WarrenDefeat, Doubles_Text_NotEnoughMons
	msgbox Route133_Text_WarrenPostBattle, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_Beck:: @ 81F75FF
	trainerbattle_double TRAINER_BECK, Route133_Text_BeckIntro, Route133_Text_BeckDefeat, Doubles_Text_NotEnoughMons
	msgbox Route133_Text_BeckPostBattle, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_Mollie:: @ 81F7616
	trainerbattle_double TRAINER_MOLLIE, Route133_Text_MollieIntro, Route133_Text_MollieDefeat, Doubles_Text_NotEnoughMons
	msgbox Route133_Text_MolliePostBattle, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_Conor:: @ 81F762D
	trainerbattle_double TRAINER_CONOR, Route133_Text_ConorIntro, Route133_Text_ConorDefeat, Doubles_Text_NotEnoughMons
	msgbox Route133_Text_ConorPostBattle, MSGBOX_AUTOCLOSE
	end

