gText_Birch_Welcome:: @ 82C897B
	.string "Hello, welcome to my hack!\p"
	.string "Currently, the entire main game\n"
	.string "has been converted to Double battles,\l"
	.string "new POKéMON have been placed in every\l"
	.string "route, and many Quality of Life\l"
	.string "features have been implemented.\p"
	.string "However, there are some bugs.\p"
	.string "Do NOT fight any rematch battles\n"
	.string "as they have not been re-done and\l"
	.string "it could potentially bug out the game\l"
	.string "and excuse the lack of animations for\l"
	.string "new moves as they haven't been finished.\p"
	.string "Enjoy and let me know what you think.$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is one of the new “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "You should check out all the\n"
	.string "different areas to see what new\l"
	.string "POKéMON you can catch.\p"
	.string "Feel free to give me suggestions\n"
	.string "for new ones to add.\p"
	.string "Lets go on with the rest of\n"
	.string "the intro then.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
